version: "3"
services:
  backend:
    build:
      context: .
    ports:
      - "5005:5000" 
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: test@12345
       MYSQL_DB: KYC

         

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"  
    environment:
            
            MYSQL_ROOT_PASSWORD: test@12345
            MYSQL_DATABASE: KYC
            MYSQL_PASSWORD: test@12345
    volumes:
       - mysql-data:/var/lib/mysql
       - .message.sql:/docker-entrypoint-initdb.d/message.sql
volumes:         
  mysql-data:

                
             
